### PR TITLE
Fix rocWMMA hipRTC example for TheRock + Windows

### PR DESCRIPTION
**Pull request by adeljo-amd**
## Motivation

Fixes hipRTC compilation error when using TheRock + Windows. 

## Technical Details

An include for `cstdint` needs to be placed before the rocWMMA header include.

## Added/Updated documentation?

- [ ] Yes
- [x] No, does not apply to this PR.

## Included Visual Studio files?

- [ ] Yes
- [x] No, does not apply to this PR.

## Submission Checklist

- [x] New examples contain proper CMake and Make files.
- [x] I have updated relevant CI workflows and the new examples are being built and tested in CI.
- [x] Check and guard against unsupported ASICs if relevant dependent libraries have limited support.
- [x] Look over the contributing guidelines at https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

### CODE REVIEW

**Review by zichguan-amd — APPROVED** [review]
LGTM, tested and works with gfx1201, TheRock & pytorch 7.1.1 Adrenalin driver. It also manifests on TheRock + Linux and the PR fixes both Linux & Windows
