### ISSUE TITLE
Can't build with ROCm/HIP 6.0.0

### ISSUE THREAD

**Issue by PPPW** [amd/rocm-examples#89]
This repo worked fine for me with ROCm/HIP 5.6.0, however when I'm trying to build it (just run `make`) with ROCm/HIP 6.0.0, I got:
```
make[2]: Entering directory '/opt/rocm-examples/HIP-Basic/opengl_interop'
/opt/rocm/bin/hipcc -std=c++17 -Wall -Wextra -I ../../Common -I ../../External   -o hip_opengl_interop main.hip ../../External/glad/glad.cpp -lglfw -ldl
main.hip:104:65: error: use of undeclared identifier 'hipGLDeviceListAll'
    HIP_CHECK(hipGLGetDevices(&gl_device_count, &hip_device, 1, hipGLDeviceListAll));
                                                                ^
main.hip:428:19: error: use of undeclared identifier 'hipGraphicsGLRegisterBuffer'
        HIP_CHECK(hipGraphicsGLRegisterBuffer(
                  ^
2 errors generated when compiling for gfx906.
make[2]: *** [Makefile:58: hip_opengl_interop] Error 1
make[2]: Leaving directory '/opt/rocm-examples/HIP-Basic/opengl_interop'
make[1]: *** [Makefile:64: opengl_interop] Error 2
make[1]: Leaving directory '/opt/rocm-examples/HIP-Basic'
make: *** [Makefile:34: HIP-Basic] Error 2
```

I searched "hipGraphicsGLRegisterBuffer" and "hipGLDeviceListAll", [they exist](https://docs.amd.com/projects/HIP/en/docs-5.7.0/.doxygen/docBin/html/group___g_l.html) in previous HIP versions however not in [latest HIP version](https://docs.amd.com/projects/HIP/en/docs-6.0.0/doxygen/html/group___g_l.html). Do we have plans to make this repo work with ROCm 6.0.0? Thanks

**Comment by Naraenda** [comment]
This is probably fixed with https://github.com/ROCm/rocm-examples/pull/99

**Comment by PPPW** [comment]
> This is probably fixed with #99

Will verify once that PR is merged.
